### ISSUE TITLE
Allow to return a blob for `getItemRaw` (http driver)

### ISSUE THREAD

**Issue by manniL** [unjs/unstorage#435] opened 2024-05-01 08:28 UTC
### Describe the feature

To fetch binary files (e.g. images), using a blob response would be helpful for the http driver

A simple and optional implementation could be:

```diff
diff --git a/drivers/http.mjs b/drivers/http.mjs
index 99a72ce2289532f7bbc52ad6ff7ec5b8755aa62c..a07d5fe496341b4e1a8e68cdd0b4cd7154270c41 100644
@@ -32,7 +33,8 @@ export default defineDriver((opts) => {
           accept: "application/octet-stream",
           ...opts.headers,
           ...topts.headers
-        }
+        },
+        responseType: topts.responseType ?? opts.responseType
       }).catch(catchFetchError);
       return value;
     },
```

### Additional information

- [x] Would you be willing to help implement this feature?

Referencing #142 for this too :)

**Comment by pi0** [comment] 2024-05-01 08:31
Please issue issues to explain **why** not **how** 🙏🏼 (eg: a user code example or reproduction)

**Comment by manniL** [comment] 2024-05-01 08:36
@pi0 Of course!

**Why**: Because if you want to fetch binary files, such as *images* from the http server `unstorage` provides, there is no way to do so with the HTTP driver and ensure the formatting is correct.

The goal would be doing something like this in the browser (or whereever):

```ts
const storage = createStorage({
  driver: httpDriver({ base: "/api/storage" }),
});

const getItem = async () => {
  const blob = await storage.getItemRaw(name.value, {
    responseType: 'blob'
  })
  const url = URL.createObjectURL(blob)
  // do more with the URL
}
```

**Comment by pi0** [comment] 2024-05-01 08:47
Thanks for explaining. 

I think it makes sense but we should consider implementing a driver-agnostic `type` (ideally via [undio](https://undio.unjs.io) supported types) rather than patching for only one driver. (HTTP driver then can respect this type and prefer native `blob` or `response` return when it can preserve blob/file information) 

`responseType` is specific to the underlying library of HTTP driver (ofetch) and we cannot rely on it nor diverge the API only for one driver support (HTTP) because it can change and unstorage API should be consistent regardless of the driver.

> If you have a better idea of solving this problem,

In the meantime, I would suggest you directly use fetch for the HTTP driver if need blob access. `raw` support is still marked as experimental for unstorage after all for the very same reason of limitations and inconsistent behavior. 

Let's track this via https://github.com/unjs/unstorage/issues/142 👍🏼 (I have updated undio note in there)

**Comment by manniL** [comment] 2024-05-01 08:48
Makes sense! Thanks for the explanation ☺️

**Closed by pi0** 2024-05-01 08:47 UTC
Labels: discussion
